apiVersion: 1

datasources:
  - name: GivEnergy
    uid: givenergy-prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 30s
