{
 "title": "GivEnergy Solar Monitor (Small)",
 "tags": [
  "givenergy",
  "solar",
  "small"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Battery Level",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "givenergy_power_battery_percent",
     "legendFormat": "Battery %"
    }
   ]
  },
  {
   "title": "Power Sources",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "givenergy_power_solar_power", "legendFormat": "Solar" },
    {
     "expr": "clamp_min(givenergy_power_battery_power, 0)",
     "legendFormat": "Battery Discharge"
    },
    {
     "expr": "clamp_min(-givenergy_power_grid_power, 0)",
     "legendFormat": "Grid Import"
    }
   ]
  },
  {
   "title": "Power Uses",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "givenergy_power_consumption_power",
     "legendFormat": "Consumption"
    },
    {
     "expr": "clamp_min(-givenergy_power_battery_power, 0)",
     "legendFormat": "Battery Charging"
    },
    {
     "expr": "clamp_min(givenergy_power_grid_power, 0)",
     "legendFormat": "Grid Export"
    }
   ]
  }
 ]
}